//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnisensTest.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.csv.SignalCsvReader")]
        public string signal_csv_reader
        {
            get
            {
                return ((string)(this["signal_csv_reader"]));
            }
            set
            {
                this["signal_csv_reader"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.csv.SignalCsvWriter")]
        public string signal_csv_writer
        {
            get
            {
                return ((string)(this["signal_csv_writer"]));
            }
            set
            {
                this["signal_csv_writer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.bin.SignalBinReader")]
        public string signal_bin_reader
        {
            get
            {
                return ((string)(this["signal_bin_reader"]));
            }
            set
            {
                this["signal_bin_reader"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.bin.SignalBinWriter")]
        public string signal_bin_writer
        {
            get
            {
                return ((string)(this["signal_bin_writer"]));
            }
            set
            {
                this["signal_bin_writer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.xml.SignalXmlReader")]
        public string signal_xml_reader
        {
            get
            {
                return ((string)(this["signal_xml_reader"]));
            }
            set
            {
                this["signal_xml_reader"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.xml.SignalXmlWriter")]
        public string signal_xml_writer
        {
            get
            {
                return ((string)(this["signal_xml_writer"]));
            }
            set
            {
                this["signal_xml_writer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.csv.ValuesCsvReader")]
        public string values_csv_reader
        {
            get
            {
                return ((string)(this["values_csv_reader"]));
            }
            set
            {
                this["values_csv_reader"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.csv.ValuesCsvWriter")]
        public string values_csv_writer
        {
            get
            {
                return ((string)(this["values_csv_writer"]));
            }
            set
            {
                this["values_csv_writer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.bin.ValuesBinReader")]
        public string values_bin_reader
        {
            get
            {
                return ((string)(this["values_bin_reader"]));
            }
            set
            {
                this["values_bin_reader"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.bin.ValuesBinWriter")]
        public string values_bin_writer
        {
            get
            {
                return ((string)(this["values_bin_writer"]));
            }
            set
            {
                this["values_bin_writer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.xml.ValuesXmlReader")]
        public string values_xml_reader
        {
            get
            {
                return ((string)(this["values_xml_reader"]));
            }
            set
            {
                this["values_xml_reader"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.xml.ValuesXmlWriter")]
        public string values_xml_writer
        {
            get
            {
                return ((string)(this["values_xml_writer"]));
            }
            set
            {
                this["values_xml_writer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.csv.EventCsvReader")]
        public string event_csv_reader
        {
            get
            {
                return ((string)(this["event_csv_reader"]));
            }
            set
            {
                this["event_csv_reader"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.csv.EventCsvWriter")]
        public string event_csv_writer
        {
            get
            {
                return ((string)(this["event_csv_writer"]));
            }
            set
            {
                this["event_csv_writer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.bin.EventBinReader")]
        public string event_bin_reader
        {
            get
            {
                return ((string)(this["event_bin_reader"]));
            }
            set
            {
                this["event_bin_reader"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.bin.EventBinWriter")]
        public string event_bin_writer
        {
            get
            {
                return ((string)(this["event_bin_writer"]));
            }
            set
            {
                this["event_bin_writer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.xml.EventXmlReader")]
        public string event_xml_reader
        {
            get
            {
                return ((string)(this["event_xml_reader"]));
            }
            set
            {
                this["event_xml_reader"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.io.xml.EventXmlWriter")]
        public string event_xml_writer
        {
            get
            {
                return ((string)(this["event_xml_writer"]));
            }
            set
            {
                this["event_xml_writer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool validation
        {
            get
            {
                return ((bool)(this["validation"]));
            }
            set
            {
                this["validation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("org.unisens.ri.UnisensFactoryImpl")]
        public string StandardUnisensFactoryClass
        {
            get
            {
                return ((string)(this["StandardUnisensFactoryClass"]));
            }
            set
            {
                this["StandardUnisensFactoryClass"] = value;
            }
        }
    }
}
